api_platform:
#    defaults:
#        pagination_items_per_page: 10
#        pagination_enabled: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
#    collection:
#        pagination:
#            items_per_page: 5

