version: '3'
services:
   db:
     image: mysql:5.7
     container_name: db
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test
        MYSQL_USER: app
        MYSQL_PASSWORD: app
     ports:
        - "3306"

# php-app:
#      container_name: app
#      build:
#           context: ./docker/php-fpm
#           dockerfile: Dockerfile
#      depends_on:
#           - db
#      expose:
#           - "9000"
#      volumes:
#           - .:/app:cached
#           - ./docker/php-fpm/resolv.conf:/etc/resolv.conf
#           - ${SSH_KEY:-~/.ssh/id_rsa}:/root/.ssh/id_rsa

# nginx:
#      build:
#           context: ./docker/nginx
#           dockerfile: Dockerfile
#           container_name: webserver
#           ports:
#                - "8082:80"
#           links:
#                - app
#           volumes:
#                - .:/app:cached
#                - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf